# -*- coding: utf-8 -*-
"""Advance task 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aIkVg6ecodzYu6GaKECwduP7k8h1wLWH
"""

print(df.columns.tolist())

import pandas as pd
import plotly.express as px

# Load Data
df = pd.read_csv('/content/archive_6.zip')  # replace with your filename

# Clean & Convert
df['Order.Date'] = pd.to_datetime(df['Order.Date'])
df['Ship.Date'] = pd.to_datetime(df['Ship.Date'])

# Sidebar Filters
st.sidebar.title("🔎 Filter Options")
region = st.sidebar.multiselect("Select Region", options=df['Region'].unique(), default=df['Region'].unique())
category = st.sidebar.multiselect("Select Category", options=df['Category'].unique(), default=df['Category'].unique())
sub_category = st.sidebar.multiselect("Select Sub-Category", options=df['Sub.Category'].unique(), default=df['Sub.Category'].unique())

# Apply Filters
filtered_df = df[
    (df['Region'].isin(region)) &
    (df['Category'].isin(category)) &
    (df['Sub.Category'].isin(sub_category))
]

# Title
st.title("📊 Superstore Sales Dashboard")

# KPIs
total_sales = filtered_df['Sales'].sum()
total_profit = filtered_df['Profit'].sum()
top_customers = filtered_df.groupby('Customer.Name')['Sales'].sum().sort_values(ascending=False).head(5)

# KPI Display
col1, col2 = st.columns(2)
col1.metric("💰 Total Sales", f"${total_sales:,.0f}")
col2.metric("📈 Total Profit", f"${total_profit:,.0f}")

# Charts
st.subheader("🧑‍💼 Top 5 Customers by Sales")
st.bar_chart(top_customers)

# Optional: Monthly Sales Trend
monthly_sales = filtered_df.resample('M', on='Order.Date')['Sales'].sum()
st.subheader("📆 Monthly Sales Trend")
fig = px.line(monthly_sales, title='Monthly Sales')
st.plotly_chart(fig)

